name = "MinimaxAI"
uuid = "875d37ae-5a47-4198-bc26-2c772ca055d4"
authors = ["David Arnold"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
